apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  type: NodePort
  selector:
    app: cv-app
  ports:
    - protocol: TCP
      port: 80          # Port interne du service
      targetPort: 80    # Port du conteneur
      nodePort: 30001   # Port accessible depuis ton navigateur
